name: Github 2 Dockerhub 2 Slack
on:
  push:
    # types: [published]
    # tag:
    # - v1.*

jobs:
  build_and_upload:
    runs-on: ubuntu-latest

    
    steps:

      # https://github.com/marketplace/actions/checkout
      - name: Checkout the code from github repo
        uses: actions/checkout@v3
    
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
    
    # - name: Build and push
    #   uses: docker/build-push-action@v2
    #   with:
    #     push: true
    #     tags: ${{ github.repository }}:${{ github.ref_name }}

    # - name: Send custom JSON data to Slack workflow
    #   id: slack
    #   uses: slackapi/slack-github-action@v1.18.0
    #   with:
    #     # For posting a rich message using Block Kit
    #     payload: |
    #       {
    #         "text": "SA54 Submission",
    #         "blocks": [
    #           {
    #             "type": "section",
    #             "text": {
    #               "type": "mrkdwn",
    #               "text": "Name: ${{secrets.USER_NAME}}\nMatriculation Number: ${{secrets.MAT_NUMBER}}\nEmail: ${{secrets.EMAIL}}\nRepository: ${{ github.repositoryUrl }}\nImage Name: ${{ github.repository }}:${{ github.ref_name }}\nImage URL: ${{secrets.IMAGE_URL}}"
    #             }
    #           }
    #         ]
    #       }
    #   env:
    #     SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
    #     SLACK_WEBHOOK_TYPE: INCOMING_WEBHOOK