name: Github 2 Dockerhub 2 Slack
on:
  push:
    # types: [published]
    # tag:
    # - v1.*

jobs:
  build_and_upload:
    runs-on: ubuntu-latest

    
    steps:

     
      - name: Checkout the code from github repo
        uses: actions/checkout@v3
    
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
    
      - name: Build and push
        uses: docker/build-push-action@v3
        with:
          push: true
          tags: liiiuyuanhao/sa54_cicd:v2.1.2
      

      - name: Post message on slack
              uses: bluenovaio/action-slack@master
              with:
                username: "LIU Yuanhao"
                icon_emoji: ":CICD_Image:"
                text:  "${{secrets.SLACK_MSG}} \nRepo: ${{ github.repositoryUrl }}\nImage name: ${{ secrets.DOCKERHUB_USERNAME }}/randimg:${{github.ref_name}}\nImage url: https://hub.docker.com/repository/docker/liiiuyuanhao/sa54_cicd"
                webhook_url: ${{ secrets.SLACK_WEBHOOK }}
© 2022 GitHub, Inc.
Terms
Privacy
Security
Status
Docs
Contact GitHub
